[package]
name = "frontend"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
gloo-net = { version = "0.6.0", features = ["json"] }
leptos = { version = "0.8", features = ["csr"] }
serde = { version = "1.0.228", features = ["derive"] }
shared = { path = "../shared" }
uuid = { version = "1.23.1", features = ["serde"] }
